# Generated by Django 4.0.2 on 2023-09-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('na', models.CharField(max_length=100)),
                ('em', models.CharField(max_length=100)),
                ('pd', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
